Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-10, with the labels that each got.

#83 no logging if there is no pre-/post-patch step output
  ospatch/exec_step.go
Labels: approved, lgtm, size/XS

#79 Move ospatch to ospatchog, cleanup WUA library
  inventory/packages/wua_windows.go
  main.go
  ospatch/patch_run_test.go
  ospatchog/apt_upgrade.go
  ospatchog/exec_step.go
  ospatchog/exec_step_linux.go
  ospatchog/exec_step_windows.go
  ospatchog/googet_update.go
  ospatchog/patch_run.go
  ospatchog/patch_state.go
  ospatchog/patch_state_test.go
  ospatchog/runner.go
  ospatchog/system_linux.go
  ospatchog/system_test_stub.go
  ospatchog/system_windows.go
  ospatchog/updates.go
  ospatchog/updates_linux.go
  ospatchog/updates_test.go
  ospatchog/updates_test_stub.go
  ospatchog/updates_windows.go
  ospatchog/watcher.go
  ospatchog/watcher_test.go
  ospatchog/yum_update.go
  ospatchog/zypper_patch.go
Labels: approved, lgtm, size/L

#84 Add basic agentendpoint logic
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/patch_task.go
  agentendpoint/retry.go
  agentendpoint/task_state.go
  agentendpoint/task_state_test.go
  config/config.go
  tasker/tasker.go
Labels: approved, lgtm, size/XXL

#86 Add exec task to agent endpoint
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
Labels: approved, lgtm, size/L

#87 Fork ospatch to work with agentendpoint
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/runner.go
  ospatch/system_linux.go
  ospatch/system_test_stub.go
  ospatch/system_windows.go
  ospatch/updates.go
  ospatch/updates_linux.go
  ospatch/updates_test.go
  ospatch/updates_test_stub.go
  ospatch/updates_windows.go
  ospatch/yum_update.go
  ospatch/zypper_patch.go
Labels: approved, lgtm, size/XXL

#85 bugfixes for windows
  policies/recipes/recipedb.go
  policies/recipes/steps.go
  policies/recipes/steps_linux.go
  policies/recipes/steps_windows.go
Labels: approved, lgtm, size/M

#89 Connect agentendpoint and ospatch
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/reboot_linux.go
  agentendpoint/reboot_windows.go
Labels: approved, lgtm, size/L

#91 Update logging, add agentendpoint command to the binary
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L

#90 set a PowerShell execution policy when running an OS Config pre-/post-patch task
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  ospatchog/exec_step_windows.go
Labels: approved, lgtm, size/S

#88 Add beginnings of includes/excludes for package management
  agentendpoint/patch_linux.go
  inventory/packages/apt_deb.go
  inventory/packages/apt_deb_test.go
  inventory/packages/packages_linux.go
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/system_linux.go
  ospatch/system_windows.go
  ospatch/updates.go
Labels: approved, lgtm, size/L

#92 Fix bugs in agentendpoint code
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_task.go
  agentendpoint/retry.go
  config/config.go
  go.mod
  go.sum
  main.go
  util/util.go
Labels: approved, lgtm, size/L
