Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-05, with the labels that each got.

#8 Add OWNERS file
  OWNERS
  inventory/inventory.go
  main.go
  ospackage/apt.go
  ospackage/googet.go
  ospackage/ospackage.go
  ospackage/yum.go
  ospackage/zypper.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/M

#9 Copy over osinfo, service, and packages libraries.
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/os_configs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_jobs.pb.go
  go.mod
  go.sum
  inventory/inventory.go
  inventory/inventory_test.go
  inventory/osinfo/osinfo.go
  inventory/osinfo/osinfo_linux.go
  inventory/osinfo/osinfo_windows.go
  inventory/packages/apt_deb.go
  inventory/packages/apt_deb_test.go
  inventory/packages/gem.go
  inventory/packages/googet.go
  inventory/packages/googet_test.go
  inventory/packages/packages.go
  inventory/packages/packages_linux.go
  inventory/packages/packages_test.go
  inventory/packages/packages_windows.go
  inventory/packages/pip.go
  inventory/packages/qfe_windows.go
  inventory/packages/rpm.go
  inventory/packages/wua_windows.go
  inventory/packages/yum.go
  inventory/packages/yum_test.go
  inventory/packages/zypper.go
  inventory/packages/zypper_test.go
  main.go
  ospackage/apt.go
  ospackage/changes.go
  ospackage/changes_test.go
  ospackage/googet.go
  ospackage/ospackage.go
  ospackage/yum.go
  ospackage/zypper.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
  service/service.go
Labels: approved, lgtm, size/XXL

#11 Update packaging to work with go modules
  CONTRIBUTING.md
  LICENSE
  OWNERS
  go.mod
  go.sum
  packaging/build_packages_deb.sh
  packaging/build_packages_goo.sh
  packaging/build_packages_rpm.sh
  packaging/common.sh
  packaging/debian/rules
  packaging/googet/build.sh
  packaging/googet/google-osconfig-agent.goospec
  packaging/google-osconfig-agent.spec
  packaging/setup_deb.sh
  packaging/setup_goo.sh
Labels: approved, lgtm, size/L

#12 Fix a few bugs in patch
  ospatch/patch_run.go
  ospatch/system_linux.go
  ospatch/system_windows.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/L

#13 update package version
  packaging/common.sh
  packaging/debian/changelog
  packaging/googet/google-osconfig-agent.goospec
Labels: approved, lgtm, size/S

#15 Add Liam as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#18 Add basic retries, update inventory after a patch run
  ospatch/patch_run.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/S

#17 Update googet build to use version variable
  ospatch/patch_run.go
  packaging/googet/build.sh
  packaging/googet/google-osconfig-agent.goospec
  packaging/setup_goo.sh
Labels: approved, lgtm, size/S

#16 Update to shared logger library
  go.mod
  go.sum
  inventory/inventory.go
  lock_linux.go
  lock_windows.go
  logger/logger.go
  main.go
  ospackage/apt.go
  ospackage/googet.go
  ospackage/ospackage.go
  ospackage/yum.go
  ospackage/zypper.go
  ospatch/patch_run.go
  ospatch/system_linux.go
  ospatch/system_windows.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
  ospatch/watcher.go
  packaging/build_packages_deb.sh
  tasker/tasker.go
Labels: approved, lgtm, size/L

#20 Respect apt and yum special options for patch + bug fixes
  config/config.go
  inventory/inventory.go
  inventory/packages/apt_deb.go
  inventory/packages/packages_linux.go
  inventory/packages/packages_windows.go
  inventory/packages/wua_windows.go
  inventory/packages/yum.go
  inventory/packages/zypper.go
  main.go
  ospatch/patch_run.go
  ospatch/patch_state_test.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
  packaging/build_packages_rpm.sh
Labels: approved, lgtm, size/L

#21 Bug fixes and logging improvements
  go.mod
  go.sum
  inventory/packages/apt_deb.go
  inventory/packages/googet.go
  inventory/packages/zypper.go
  inventory/packages/zypper_test.go
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/patch_run.go
  ospatch/patch_state.go
  ospatch/patch_state_test.go
  ospatch/runner.go
  ospatch/system_linux.go
  ospatch/system_windows.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
  ospatch/yum_update.go
  ospatch/zypper_update.go
Labels: approved, lgtm, size/XL

#23 Report inventory LastUpdated last, update inventory and debug metadata keys
  config/config.go
  config/config_test.go
  inventory/inventory.go
  ospatch/patch_run.go
Labels: approved, lgtm, size/M

#24 Fix up reboot indicators and logging
  inventory/packages/yum.go
  ospatch/patch_run.go
  ospatch/system_linux.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/L
