Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-07, with the labels that each got.

#33 Use v1alpha2, WUA: accept unaccepted EULAs
  go.mod
  go.sum
  ospatch/patch_run.go
  ospatch/patch_state_test.go
  ospatch/system_test_stub.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/L

#34 Update version to 1.0.0 to beta inventory release
  packaging/common.sh
  packaging/debian/changelog
  packaging/googet/google-osconfig-agent.goospec
Labels: approved, lgtm, size/XS

#31 Recipes
  ospackage/recipes/buildcommand.go
  ospackage/recipes/installrecipe.go
  ospackage/recipes/recipedb.go
  ospackage/recipes/stub.go
Labels: approved, lgtm, size/L

#32 adding support for fetching artifacts for software recipes
  go.mod
  go.sum
  ospackage/recipes/artifacts.go
  ospackage/recipes/installrecipe.go
  ospackage/recipes/stub.go
Labels: approved, lgtm, size/L

#40 add liam as guest policies approver
  policies/OWNERS
Labels: approved, lgtm, size/XS

#39 update protos for recipe changes
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha2/os_config_client.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/guest_policies.pb.go
  policies/recipes/artifacts.go
Labels: approved, lgtm, size/XL

#42 adding recipedb code
  go.mod
  go.sum
  policies/recipes/installrecipe.go
  policies/recipes/recipedb.go
Labels: approved, lgtm, size/M

#45 Add apt key management and rpm reboot required signal
  go.mod
  go.sum
  inventory/packages/packages.go
  inventory/packages/rpm.go
  ospatch/system_linux.go
  ospatch/updates.go
  ospatch/updates_linux.go
  ospatch/updates_test.go
  packaging/common.sh
  packaging/debian/changelog
  packaging/googet/google-osconfig-agent.goospec
  policies/apt.go
  policies/policies.go
Labels: approved, lgtm, size/L
