Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-11, with the labels that each got.

#95 Update retry logic to handle ResourceExhausted backoff
  agentendpoint/retry.go
Labels: approved, lgtm, size/S

#96 Apt parsing and WUA library fixes
  inventory/packages/apt_deb.go
  inventory/packages/apt_deb_test.go
  inventory/packages/wua_windows.go
Labels: approved, lgtm, size/M

#99 Make Exclusive Packages and DryRun work in Yum
  inventory/packages/yum.go
  inventory/packages/yum_test.go
  ospatch/apt_upgrade.go
  ospatch/yum_update.go
Labels: approved, lgtm, size/L

#97 Sync in latest API changes, allow for WaitForTaskNotification to be canceled
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/agent_endpoint_client.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/agentendpoint.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/patch_jobs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_task.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#100 Update waitForTask error handling
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
Labels: approved, lgtm, size/M

#102 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#94 Use the agentendpoint for patch and guestpolicies
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/doc.go
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client.go
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha2/doc.go
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha2/os_config_client.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/assignments.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/os_configs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/osconfig_service.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_jobs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/osconfig_service.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/patch_jobs.pb.go
  config/config.go
  config/config_test.go
  main.go
  ospatchog/apt_upgrade.go
  ospatchog/exec_step.go
  ospatchog/exec_step_linux.go
  ospatchog/exec_step_windows.go
  ospatchog/googet_update.go
  ospatchog/patch_run.go
  ospatchog/patch_state.go
  ospatchog/patch_state_test.go
  ospatchog/runner.go
  ospatchog/system_linux.go
  ospatchog/system_test_stub.go
  ospatchog/system_windows.go
  ospatchog/updates.go
  ospatchog/updates_linux.go
  ospatchog/updates_test.go
  ospatchog/updates_test_stub.go
  ospatchog/updates_windows.go
  ospatchog/watcher.go
  ospatchog/watcher_test.go
  ospatchog/yum_update.go
  ospatchog/zypper_patch.go
  packaging/common.sh
  packaging/debian/changelog
  policies/apt.go
  policies/apt_test.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/googet_test.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
  tasker/tasker.go
Labels: approved, lgtm, size/XXL

#101 Implement exclusive_patches for windows
  agentendpoint/patch_windows.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/M

#105 Move e2e_tests into the osconfig repo
  e2e_tests/Dockerfile
  e2e_tests/_internal/cloud.google.com/go/osconfig/apiv1alpha2/doc.go
  e2e_tests/_internal/cloud.google.com/go/osconfig/apiv1alpha2/os_config_client.go
  e2e_tests/_internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/guest_policies.pb.go
  e2e_tests/_internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/osconfig_service.pb.go
  e2e_tests/_internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/patch_jobs.pb.go
  e2e_tests/cloudbuild.yaml
  e2e_tests/compute/instance.go
  e2e_tests/config/config.go
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/main.go
  e2e_tests/osconfig_server/osconfig_data_builder.go
  e2e_tests/test_config/project_config.go
  e2e_tests/test_config/project_config_test.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/test_suites/patch/test_setup.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XXL

#106 Fix cloudbuild for e2e_tests
  e2e_tests/cloudbuild.yaml
Labels: approved, lgtm, size/XS

#103 Implement Windows service directly, handle systemd stop signal
  go.mod
  go.sum
  google-osconfig-agent.service
  main.go
  main_linux.go
  main_windows.go
  service/service.go
Labels: approved, lgtm, size/L

#108 Fix YUM output parsing
  agentendpoint/agentendpoint.go
  go.mod
  go.sum
  inventory/packages/pty_linux.go
  inventory/packages/stub.go
  inventory/packages/yum.go
  inventory/packages/yum_test.go
  main.go
Labels: approved, lgtm, size/L

#109 e2e_tests: Attempt to deflake Windows agent install
  e2e_tests/go.sum
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#107 Implement patch whitelisting for zypper
  inventory/packages/zypper.go
  inventory/packages/zypper_test.go
  ospatch/apt_upgrade.go
  ospatch/updates.go
  ospatch/zypper_patch.go
Labels: approved, lgtm, size/XL

#110 Fix panic, add recover for edge cases.
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  inventory/packages/wua_windows.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/S

#111 Add tests for patch whitelisting
  e2e_tests/go.sum
  e2e_tests/test_suites/patch/patch.go
  ospatch/zypper_patch.go
  ospatch/zypper_patch_test.go
Labels: approved, lgtm, size/L

#112 Update Windows update install logic
  agentendpoint/patch_windows.go
  e2e_tests/utils/utils.go
  go.sum
Labels: approved, lgtm, size/M
