Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-08, with the labels that each got.

#46 Fix a few inventory bugs, add EL8 build
  inventory/packages/apt_deb.go
  inventory/packages/gem.go
  inventory/packages/googet.go
  inventory/packages/pip.go
  inventory/packages/rpm.go
  inventory/packages/yum.go
  inventory/packages/zypper.go
  main.go
  packaging/build_packages_wf.json
  packaging/daisy_startupscript_rpm.sh
  packaging/google-osconfig-agent.spec
Labels: approved, lgtm, size/L

#44 adding windows support to script and file execution
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
Labels: approved, lgtm, size/M

#49 add pre-/post-patch step protodefs and remove version from guest policies protodef
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/osconfig_service.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/patch_jobs.pb.go
Labels: approved, lgtm, size/XXL

#47 Add more tests for inventory functions
  inventory/packages/apt_deb.go
  inventory/packages/apt_deb_test.go
  inventory/packages/googet.go
  inventory/packages/googet_test.go
  inventory/packages/rpm.go
  inventory/packages/rpm_test.go
  inventory/packages/yum.go
  inventory/packages/yum_test.go
  inventory/packages/zypper.go
  inventory/packages/zypper_test.go
Labels: approved, lgtm, size/XL

#48 Add zypper patch support, pretty print requests/responses
  common/common.go
  go.mod
  go.sum
  main.go
  ospatch/patch_run.go
  ospatch/updates.go
  ospatch/updates_linux.go
  ospatch/watcher_test.go
  ospatch/zypper_patch.go
  ospatch/zypper_update.go
  policies/policies.go
Labels: approved, lgtm, size/L

#51 version bump
  packaging/common.sh
  packaging/debian/changelog
  packaging/google-osconfig-agent.spec
Labels: approved, lgtm, size/S

#50 add empty pre-/post-patch steps to patch run
  ospatch/patch_run.go
Labels: approved, lgtm, size/M

#52 move artifact fetching logic to common
  common/common.go
  packaging/README.md
  policies/recipes/artifacts.go
  policies/recipes/steps.go
Labels: approved, lgtm, size/L

#55 Add ZypperPatches to inventory
  google-osconfig-agent.service
  inventory/packages/packages.go
  inventory/packages/packages_linux.go
  inventory/packages/zypper.go
  inventory/packages/zypper_test.go
  packaging/common.sh
  packaging/debian/changelog
  packaging/googet/google-osconfig-agent.goospec
  packaging/googet/install.ps1
Labels: approved, lgtm, size/L

#56 Improve unit test coverage
  common/common.go
  inventory/osinfo/osinfo_linux.go
  inventory/osinfo/osinfo_linux_test.go
  inventory/packages/apt_deb.go
  inventory/packages/gem.go
  inventory/packages/googet.go
  inventory/packages/packages.go
  inventory/packages/packages_linux.go
  inventory/packages/packages_windows.go
  inventory/packages/pip.go
  inventory/packages/yum.go
  inventory/packages/zypper.go
  ospatch/system_linux.go
  ospatch/updates.go
  ospatch/updates_linux.go
Labels: approved, lgtm, size/L
