Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-12, with the labels that each got.

#114 Update sles old images
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#113 Implement logic to parse and merge VM instance software configs.
  policies/local.go
  policies/local_test.go
Labels: approved, lgtm, ok-to-test, size/L

#115 Update agent to use v1beta api
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1beta/agent_endpoint_client.go
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1beta/doc.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/agentendpoint.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/patch_jobs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/tasks.pb.go
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  go.mod
  go.sum
  policies/apt.go
  policies/apt_test.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/googet_test.go
  policies/local.go
  policies/local_test.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/recipes/steps_linux.go
  policies/recipes/steps_windows.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: approved, lgtm, size/XXL

#116 Add SoftwareRecipe tests
  e2e_tests/osconfig_server/osconfig_data_builder.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: approved, lgtm, size/L

#117 Activated the local software configs feature
  policies/local.go
  policies/local_test.go
  policies/policies.go
Labels: approved, lgtm, ok-to-test, size/M

#118 Bump version, a few fixes for beta candidate
  agentendpoint/agentendpoint.go
  config/config.go
  e2e_tests/config/config.go
  e2e_tests/main.go
  e2e_tests/test_config/project_config.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/test_suites/patch/test_setup.go
  e2e_tests/utils/utils.go
  go.sum
  ospatch/updates_windows.go
  packaging/common.sh
  packaging/debian/changelog
  policies/local.go
  policies/local_test.go
  policies/policies.go
Labels: approved, lgtm, size/L

#119 Update debian build
  e2e_tests/go.mod
  e2e_tests/go.sum
  go.mod
  go.sum
  packaging/common.sh
  packaging/debian/changelog
  packaging/debian/rules
Labels: approved, lgtm, size/L

#120 update sles image project name
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#121 Don't stream serial port in e2e_tests
  e2e_tests/compute/instance.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/patch/patch.go
Labels: approved, lgtm, size/L

#122 Fix a few bugs, bump version
  agentendpoint/agentendpoint.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/retry.go
  config/config.go
  inventory/packages/zypper.go
  ospatch/runner.go
  ospatch/zypper_patch.go
  packaging/common.sh
  packaging/debian/changelog
  policies/local.go
  policies/local_test.go
  policies/policies.go
  policies/recipes/installrecipe.go
Labels: approved, lgtm, size/L

#123 Update logic for the existance of package managers
  agentendpoint/patch_linux.go
  inventory/packages/apt_deb.go
  inventory/packages/packages.go
  inventory/packages/rpm.go
  util/util.go
Labels: approved, lgtm, size/S

#124 Update e2e_tests to only create 10 instances at a time to limit qps
  e2e_tests/compute/instance.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#125 Add SoftwareRecipe tests for Windows
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/utils/utils.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
Labels: approved, size/L

#126 Update Windows install for e2e_tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#127 Move to autogenerated libraries, update modules
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1beta/agent_endpoint_client.go
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1beta/doc.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/agentendpoint.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/patch_jobs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1beta/tasks.pb.go
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  e2e_tests/_internal/cloud.google.com/go/osconfig/apiv1alpha2/doc.go
  e2e_tests/_internal/cloud.google.com/go/osconfig/apiv1alpha2/os_config_client.go
  e2e_tests/_internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/guest_policies.pb.go
  e2e_tests/_internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/osconfig_service.pb.go
  e2e_tests/_internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/patch_jobs.pb.go
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/osconfig_server/osconfig_data_builder.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/patch/patch.go
  go.mod
  go.sum
  policies/apt.go
  policies/apt_test.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/googet_test.go
  policies/local.go
  policies/local_test.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: approved, lgtm, size/XXL
