Repository GoogleCloudPlatform/osconfig, pull requests merged in 2019-09, with the labels that each got.

#58 Connect zypper configs, update protos
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha2/os_config_client.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/agentendpoint.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/patch_jobs.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/osconfig_service.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha2/patch_jobs.pb.go
  config/config.go
  go.mod
  go.sum
  ospatch/updates_linux.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: approved, lgtm, size/XXL

#43 Update shebang and arg handling
  policies/recipes/steps.go
Labels: approved, lgtm, size/L

#54 adding support for archives
  go.mod
  go.sum
  policies/recipes/steps.go
  policies/recipes/steps_linux.go
  policies/recipes/steps_windows.go
Labels: approved, lgtm, size/L

#61 enable software recipes
  policies/policies.go
Labels: approved, lgtm, size/S

#53 add pre-/post-patch step execution for linux and windows
  common/common.go
  ospatch/exec_step.go
  ospatch/exec_step_linux.go
  ospatch/exec_step_windows.go
  ospatch/patch_run.go
Labels: approved, lgtm, size/L

#64 no upgrade in deb build
  packaging/common.sh
  packaging/daisy_startupscript_deb.sh
  packaging/daisy_startupscript_goo.sh
  packaging/debian/changelog
Labels: approved, lgtm, size/S

#65 switching default permission constant to be specified in octal
  policies/recipes/steps.go
Labels: approved, lgtm, size/XS

#59 Add fallback logic for installing/removing apt packages when applying…
  inventory/packages/apt_deb_test.go
  policies/apt.go
Labels: approved, lgtm, size/M

#70 adding file extensions (and other fixes) to RunScript step
  policies/recipes/steps.go
Labels: approved, lgtm, size/M

#63 Add tests for software recipes
  common/common.go
  external/fetcher.go
  go.mod
  go.sum
  inventory/osinfo/osinfo_linux.go
  inventory/osinfo/osinfo_linux_test.go
  inventory/packages/apt_deb.go
  inventory/packages/gem.go
  inventory/packages/googet.go
  inventory/packages/packages_linux.go
  inventory/packages/packages_windows.go
  inventory/packages/pip.go
  inventory/packages/yum.go
  inventory/packages/zypper.go
  ospatch/exec_step.go
  ospatch/exec_step_linux.go
  ospatch/exec_step_windows.go
  ospatch/patch_run.go
  ospatch/system_linux.go
  ospatch/updates_linux.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/artifacts_test.go
  policies/recipes/recipe.go
  policies/recipes/recipe_test.go
  policies/recipes/recipedb.go
  policies/recipes/recipedb_test.go
  policies/recipes/steps.go
  util/util.go
Labels: approved, lgtm, size/XXL

#60 Add more Unit tests
  attributes/attributes.go
  attributes/attributes_test.go
  config/config.go
  config/config_test.go
  tasker/tasker.go
  tasker/tasker_test.go
Labels: approved, lgtm, size/L

#66 MSI support, update step detection
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/recipe.go
  policies/recipes/recipe_test.go
  policies/recipes/recipedb.go
  policies/recipes/recipedb_test.go
  policies/recipes/steps.go
Labels: approved, lgtm, size/L

#67 Fix recipeDB init
  policies/recipes/installrecipe.go
  policies/recipes/recipe.go
  policies/recipes/recipe_test.go
  policies/recipes/recipedb.go
Labels: approved, lgtm, size/L

#71 Fix inventory error handling
  inventory/inventory.go
  inventory/packages/packages_linux.go
  inventory/packages/packages_windows.go
Labels: approved, lgtm, size/M

#68 SWR remove working directory after run
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
Labels: approved, lgtm, size/XS

#72 Fix agent stop
  service/service.go
Labels: approved, lgtm, size/XS

#73 updating version for packaging
  packaging/common.sh
Labels: approved, lgtm, size/XS

#74 Use Uname to get Linux OSInfo
  go.mod
  go.sum
  inventory/inventory.go
  inventory/osinfo/osinfo.go
  inventory/osinfo/osinfo_linux.go
  inventory/osinfo/osinfo_windows.go
  policies/policies.go
Labels: approved, lgtm, size/L

#75 Update agentendpoint library
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/agent_endpoint_client.go
  _internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/doc.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/agentendpoint.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/guest_policies.pb.go
  _internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/patch_jobs.pb.go
Labels: approved, lgtm, size/XXL

#76 Move the restart signal file to /etc/osconfig, use --gpg-auto-import-keys with Zypper
  config/config.go
  inventory/packages/zypper.go
  main.go
  packaging/common.sh
  packaging/debian/changelog
  packaging/debian/postrm
  packaging/googet/install.ps1
  packaging/google-osconfig-agent.spec
  policies/googet.go
  policies/policies.go
  policies/yum.go
  policies/zypper.go
Labels: approved, lgtm, size/M

#78 Fix exec step GCS object fetching
  ospatch/exec_step.go
  ospatch/exec_step_linux.go
  ospatch/exec_step_windows.go
Labels: approved, lgtm, size/S

#80 Trim space on hostname
  inventory/osinfo/osinfo_linux.go
Labels: approved, lgtm, size/XS

#81 Trim null characters correctly
  inventory/osinfo/osinfo_linux.go
Labels: approved, lgtm, size/XS

#77 small bugfixes
  external/fetcher.go
  ospatch/exec_step.go
  policies/recipes/artifacts.go
  policies/recipes/recipedb.go
  policies/recipes/steps.go
Labels: approved, lgtm, size/S
