Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-01, with the labels that each got.

#129 Update software recipes
  config/config.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/patch/patch.go
  inventory/packages/apt_deb.go
  inventory/packages/packages.go
  inventory/packages/rpm.go
  inventory/packages/zypper.go
  policies/local.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  util/util.go
Labels: approved, lgtm, size/L

#128 Added an e2e test for metadata-based local software configs.
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
Labels: approved, lgtm, size/M

#130 Add more checks for Windows reboot required
  ospatch/updates_windows.go
Labels: approved, lgtm, size/M

#131 Update metadata configuration
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  inventory/packages/zypper.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/L

#132 Update e2e tests
  e2e_tests/test_config/project_config.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: approved, lgtm, size/L

#134 Install systemd service and preset files in debian
  packaging/debian/rules
Labels: approved, lgtm, size/XS

#135 Fix debian/ubuntu new package install test
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: approved, lgtm, size/XS

#136 Fix data race in e2e_tests
  e2e_tests/compute/instance.go
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/test_config/project_config.go
  e2e_tests/test_config/project_config_test.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/inventory/inventory.go
Labels: approved, lgtm, size/L

#137 Update Windows test images
  e2e_tests/utils/utils.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#140 Fix typo and systemd service file
  config/config.go
  google-osconfig-agent.service
Labels: approved, lgtm, size/S

#141 Update startup logic to prevent hanging
  config/config.go
  config/config_test.go
  main.go
  packaging/debian/rules
  packaging/google-osconfig-agent.spec
Labels: approved, lgtm, size/L

#142 On restart exit with exit code 2 to ensure Windows restarts the service
  main.go
Labels: approved, lgtm, size/XS

#143 Add KernelRelease to inventory output
  inventory/inventory.go
  inventory/osinfo/osinfo.go
  inventory/osinfo/osinfo_linux.go
  inventory/osinfo/osinfo_windows.go
  inventory/packages/yum.go
Labels: approved, lgtm, size/M

#144 Update deb package build
  packaging/debian/compat
  packaging/debian/control
  packaging/debian/rules
Labels: approved, lgtm, size/S

#145 Update patch test timeouts
  e2e_tests/test_suites/patch/test_setup.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#146 Update apt repo in e2e_tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#147 Use e2 machine types for tests, disable auto updates
  agentendpoint/patch_task.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/patch/test_setup.go
  main.go
Labels: approved, lgtm, size/M
