Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-06, with the labels that each got.

#172 Fix stepExecFile chmod permissions to 0700
  policies/recipes/steps.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#173 Handle transient failures in guestpolicy operations
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/patch_beta_linux.go
  agentendpoint/patch_beta_windows.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_windows.go
  policies/policies.go
  retryutil/retry.go
Labels: approved, lgtm, size/M

#174 Run 'dpkg --configure -a' when needed.
  packages/apt_deb.go
Labels: approved, lgtm, size/M

#175 Don't check for CBS reboot required for now
  main.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/XS

#176 Log patch job after completion
  e2e_tests/test_suites/patch/patch.go
Labels: approved, lgtm, size/XS

#177 watch on osconfig specific metadata changes
  config/config.go
  config/config_test.go
Labels: approved, lgtm, size/M

#178 Add retry to test APIs
  e2e_tests/test_suites/patch/patch.go
Labels: approved, lgtm, size/S

#179 make agent talk to zonal agentendpoint
  config/config.go
  config/config_test.go
Labels: approved, lgtm, size/M

#180 update rules to not include e2e test binary
  packaging/debian/rules
Labels: approved, lgtm, size/XS
