Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-04, with the labels that each got.

#156 Add minor edits and additional links
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#158 update go.mod and go.sum after introducing agentendpoint v1 APIs
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#159 Update Windows service configuration
  packaging/googet/install.ps1
Labels: approved, lgtm, size/S

#161 fix restart required for el7, el8
  packaging/google-osconfig-agent.spec
Labels: approved, lgtm, size/XS

#160 Account for 'replacing' lines YUM package parsing
  inventory/packages/yum.go
  inventory/packages/yum_test.go
Labels: approved, lgtm, size/XS

#163 Don't disable auto updates until we have a cleaner way to control it
  main.go
Labels: approved, lgtm, size/XS

#162 Be more proactive with memory management
  agentendpoint/patch_windows.go
  inventory/inventory_test.go
  inventory/packages/wua_windows.go
  main.go
  ospatch/updates_windows.go
  packaging/googet/google-osconfig-agent.goospec
Labels: approved, lgtm, size/L

#165 Pass the package release into the build
  packaging/debian/rules
  packaging/google-osconfig-agent.spec
Labels: approved, lgtm, size/XS

#166 Reorganize osinfo and packages libraries
  agentendpoint/patch_linux.go
  agentendpoint/patch_windows.go
  agentendpointbeta/agentendpoint.go
  agentendpointbeta/patch_linux.go
  agentendpointbeta/patch_windows.go
  attributes/attributes_test.go
  go.mod
  go.sum
  inventory/inventory.go
  inventory/inventory_test.go
  main.go
  osinfo/osinfo.go
  osinfo/osinfo_linux.go
  osinfo/osinfo_linux_test.go
  osinfo/osinfo_windows.go
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/system_linux.go
  ospatch/system_windows.go
  ospatch/updates.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
  ospatch/yum_update.go
  ospatch/zypper_patch.go
  ospatch/zypper_patch_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/gem.go
  packages/googet.go
  packages/googet_test.go
  packages/packages.go
  packages/packages_linux.go
  packages/packages_test.go
  packages/packages_windows.go
  packages/pip.go
  packages/pty_linux.go
  packages/qfe_windows.go
  packages/rpm.go
  packages/rpm_test.go
  packages/stub.go
  packages/wua_windows.go
  packages/yum.go
  packages/yum_test.go
  packages/zypper.go
  packages/zypper_test.go
  policies/apt.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/policies.go
  policies/recipes/steps.go
  policies/yum.go
  policies/zypper.go
Labels: approved, lgtm, size/L

#167 Add better logging to package exec calls
  packages/apt_deb.go
  packages/googet.go
  packages/rpm.go
  packages/yum.go
  packages/zypper.go
Labels: approved, lgtm, size/L

#168 Merge V1 and Beta agentendpoint clients in the same package
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/agentendpoint_beta_test.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_beta.go
  agentendpoint/exec_task_beta_test.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_beta_linux.go
  agentendpoint/patch_beta_windows.go
  agentendpoint/patch_task.go
  agentendpoint/patch_task_beta.go
  agentendpoint/patch_windows.go
  agentendpoint/task_state.go
  agentendpoint/task_state_beta.go
  agentendpoint/task_state_beta_test.go
  agentendpoint/task_state_test.go
  agentendpointbeta/exec_task_test.go
  agentendpointbeta/reboot_linux.go
  agentendpointbeta/reboot_windows.go
  agentendpointbeta/retry.go
  go.mod
  go.sum
  policies/policies.go
Labels: approved, lgtm, size/XL

#164 poll agent config more frequently
  config/config.go
  config/config_test.go
  main.go
Labels: approved, lgtm, size/L

#169 Retry installing WUA updates until canceled or retries exceeded
  agentendpoint/patch_beta_windows.go
  agentendpoint/patch_windows.go
Labels: approved, lgtm, size/M
