Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-12, with the labels that each got.

#266 [os agent inventory] support COS reporting inventory
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#267 Pin el6 tests to last published image as it is EOL
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#269 Drop Windows 1903 and CentOS 6 from tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#268 Add ExecResource
  config/exec_resource.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/package_resource_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#270 Make sure we stop tickers
  agentconfig/agentconfig.go
  main.go
Labels: approved, lgtm, size/XS

#271 Add Ubuntu 2004 to tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#272 Carry over patch task labels during reboot, minor updates to tests, additional debug logging, allow KB prefix to excludes
  agentconfig/agentconfig.go
  agentconfig/agentconfig_test.go
  agentendpoint/agentendpoint.go
  agentendpoint/patch_task.go
  agentendpoint/task_state.go
  agentendpoint/task_state_test.go
  ospatch/updates_windows.go
Labels: approved, lgtm, size/L
