Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-11, with the labels that each got.

#243 remove feature flag for inventory reporting
  agentconfig/agentconfig.go
  agentendpoint/inventory.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Labels: approved, lgtm, size/S

#249 Add software recipe tests for COS
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: approved, lgtm, size/M

#250 complete ExecTask as no-op when the ExecStepConfig doesn't match the OS
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
Labels: approved, lgtm, size/S

#251 stop logging instance identity token as part of ReportInventory request and remove feature-flag setting in OSInventoryReporting e2e tests
  agentendpoint/agentendpoint.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Labels: approved, lgtm, size/XS

#252 add additional debug logging for ReportInventory request payload for e2e tests
  agentendpoint/agentendpoint.go
  agentendpoint/inventory.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Labels: approved, lgtm, size/XS

#253 use retryutil for ReportInventory call
  agentendpoint/inventory.go
Labels: approved, lgtm, size/M

#254 Don't return on a windows update error
  agentendpoint/patch_windows.go
Labels: approved, lgtm, size/XS

#255 update ReportInventory e2e test regexes
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Labels: approved, lgtm, size/XS

#257 Add msi functionality to PackageResource
  config/config_test.go
  config/package_resource.go
  e2e_tests/utils/utils.go
  go.mod
  go.sum
  packages/msi_windows.go
  packages/packages.go
  packages/packages_windows.go
  packages/stub_linux.go
  packages/stub_windows.go
  packages/wua_windows.go
Labels: approved, lgtm, size/L

#259 Update test Windows images
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#260 Ignore Unavailable errors on stream receive
  agentendpoint/agentendpoint.go
Labels: approved, lgtm, size/XS
