Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-08, with the labels that each got.

#191 Add context logging, make sure any actions the agent takes are logged at info level
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/exec_task.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  clog/clog.go
  config/config.go
  go.mod
  go.sum
  inventory/inventory.go
  inventory/inventory_test.go
  main.go
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/system_linux.go
  ospatch/system_windows.go
  ospatch/updates_linux.go
  ospatch/updates_windows.go
  ospatch/yum_update.go
  ospatch/zypper_patch.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/gem.go
  packages/googet.go
  packages/googet_test.go
  packages/packages.go
  packages/packages_linux.go
  packages/packages_test.go
  packages/packages_windows.go
  packages/pip.go
  packages/qfe_windows.go
  packages/rpm.go
  packages/rpm_test.go
  packages/wua_windows.go
  packages/yum.go
  packages/yum_test.go
  packages/zypper.go
  packages/zypper_test.go
  policies/apt.go
  policies/apt_test.go
  policies/googet.go
  policies/googet_test.go
  policies/local.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
  retryutil/retry.go
  tasker/tasker.go
  tasker/tasker_test.go
Labels: approved, lgtm, size/XXL

#202 Update proto library to include resources
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/resources.pb.go
Labels: approved, lgtm, size/XXL

#204 fix missing yum flags passed during yum update
  go.mod
  packages/packages.go
  packages/yum.go
  packages/yum_test.go
  util/mocks/mock_command_runner.go
  util/util.go
Labels: approved, lgtm, size/L

#206 Ensure exec tasks always send completed message on error
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
Labels: approved, lgtm, size/S

#207 Replace last remaining logger call, update dependencies
  agentendpoint/agentendpoint.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/test_suites/patch/patch.go
  go.mod
  go.sum
  packages/wua_windows.go
Labels: approved, lgtm, size/L

#205 make yum fetch updates with excludes
  ospatch/yum_update.go
  ospatch/yum_update_test.go
  packages/packages.go
  packages/yum.go
  packages/yum_test.go
Labels: approved, lgtm, size/L

#208 Fix clog panic
  clog/clog.go
  clog/clog_test.go
Labels: approved, lgtm, size/M

#209 Sync latest client libraries
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/agentendpoint.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/inventory.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
Labels: approved, lgtm, size/XXL

#210 Fix WatchMetadata web error handling, fix clog CallDepth
  clog/clog.go
  config/config.go
Labels: approved, lgtm, size/S

#211 Ensure WaitForTaskNotification runs before anything else
  main.go
Labels: approved, lgtm, size/M

#213 retrieve WUA MoreInfoURLs for inventory
  packages/packages.go
  packages/wua_windows.go
Labels: approved, lgtm, size/M

#214 merge from master
  packages/packages.go
  packages/wua_windows.go
Labels: approved, lgtm, size/M

#203 report inventory to agent endpoint
  agentendpoint/agentendpoint.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  agentendpoint/patch_task.go
  inventory/inventory.go
  inventory/inventory_test.go
  main.go
Labels: approved, lgtm, size/XL

#215 e2e_tests: add cos head image tests
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#216 e2e_tests: dont test "old" images in "head" image tests
  e2e_tests/test_suites/patch/patch.go
Labels: approved, lgtm, size/S

#217 Create temp directory per recipe run
  policies/recipes/installrecipe.go
Labels: approved, lgtm, size/S

#218 Add framework for config task
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/exec_task.go
  agentendpoint/inventory_test.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/inventory.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
Labels: approved, lgtm, size/XXL

#219 Fix panic if any osinfo calls fail
  osinfo/osinfo_linux.go
  osinfo/osinfo_windows.go
  packages/qfe_windows.go
Labels: approved, lgtm, size/M

#220 Remove unneeded "*" from recipe TempDir call
  policies/recipes/installrecipe.go
Labels: approved, lgtm, size/XS

#221 Move all packages run calls to CommandRunner
  go.mod
  ospatch/yum_update_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/gem.go
  packages/googet.go
  packages/googet_test.go
  packages/packages.go
  packages/packages_linux.go
  packages/pip.go
  packages/pty_linux.go
  packages/rpm.go
  packages/rpm_test.go
  packages/stub.go
  packages/yum.go
  packages/yum_test.go
  packages/zypper.go
  packages/zypper_test.go
  util/mocks/mock_command_runner.go
  util/util.go
Labels: approved, lgtm, size/XL

#222 Add all license files to packages
  THIRD_PARTY_LICENSES/cloud.google.com/go/LICENSE
  THIRD_PARTY_LICENSES/cloud.google.com/go/logging/LICENSE
  THIRD_PARTY_LICENSES/cloud.google.com/go/storage/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-logging-go/logger/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/osconfig/LICENSE
  THIRD_PARTY_LICENSES/github.com/golang/groupcache/lru/LICENSE
  THIRD_PARTY_LICENSES/github.com/golang/protobuf/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/go-cmp/cmp/LICENSE
  THIRD_PARTY_LICENSES/github.com/googleapis/gax-go/v2/LICENSE
  THIRD_PARTY_LICENSES/github.com/tarm/serial/LICENSE
  THIRD_PARTY_LICENSES/github.com/ulikunitz/xz/LICENSE
  THIRD_PARTY_LICENSES/go.opencensus.io/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/crypto/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/net/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/oauth2/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/sync/semaphore/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/sys/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/text/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/api/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/api/internal/third_party/uritemplates/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/genproto/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/grpc/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/protobuf/LICENSE
  go.mod
  go.sum
  packaging/README.md
  packaging/debian/google-osconfig-agent.docs
  packaging/googet/google-osconfig-agent.goospec
  packaging/google-osconfig-agent.spec
Labels: approved, lgtm, size/XXL

#223 Make sure we retry on failed Windows Updates
  agentendpoint/patch_windows.go
Labels: approved, lgtm, size/XS
