Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-10, with the labels that each got.

#236 Report installed packages on COS
  go.mod
  go.sum
  packages/cos_linux.go
  packages/cos_linux_test.go
  packages/packages.go
  packages/packages_linux.go
Labels: approved, lgtm, ok-to-test, size/L

#237 add initial e2e tests for inventory reporting
  e2e_tests/compute/instance.go
  e2e_tests/go.sum
  e2e_tests/main.go
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  go.sum
Labels: approved, lgtm, size/L

#240 add debug logging for report inventory response
  agentendpoint/inventory.go
Labels: approved, lgtm, size/S

#238 Add FileResource
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/exec_task.go
  config/config.go
  config/file.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/repository_resource.go
  external/fetcher.go
  go.mod
  policies/recipes/artifacts.go
  util/util.go
Labels: approved, lgtm, size/XL

#239 Make inventory WUAUpdates call spawn a new process, retry on metadata unmarshal error
  agentconfig/agentconfig.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  attributes/attributes.go
  attributes/attributes_test.go
  inventory/inventory.go
  main.go
  main_linux.go
  main_windows.go
  packages/packages_linux.go
  packages/packages_windows.go
Labels: approved, lgtm, size/L

#242 Ensure we record epoch for rpm packages
  packages/rpm.go
Labels: approved, lgtm, size/XS

#241 Add sleep after Unavailable errors for agentendpoint
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
Labels: approved, lgtm, size/M

#244 Pull in latest protos
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  config/config.go
  config/file.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/package_resource_test.go
  config/repository_resource.go
  config/repository_resource_test.go
  go.mod
  go.sum
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/agent_endpoint_client.go
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/doc.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/inventory.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
Labels: approved, lgtm, size/XXL

#245 Merge 'master' into development
  agentconfig/agentconfig.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  go.mod
  go.sum
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/inventory.pb.go
  packages/cos_linux.go
  packages/cos_linux_test.go
  packages/packages.go
  packages/packages_linux.go
  packaging/googet/google-osconfig-agent.goospec
Labels: approved, do-not-merge/hold, lgtm, size/XL

#247 Force yum to never colorize output
  ospatch/yum_update_test.go
  packages/yum.go
Labels: approved, lgtm, size/XS

#246 Support deb and rpm in PackageResource
  config/file_resource.go
  config/package_resource.go
  config/package_resource_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/packages_linux.go
  packages/rpm.go
  packages/rpm_test.go
Labels: approved, lgtm, size/L
