Repository GoogleCloudPlatform/osconfig, pull requests merged in 2020-07, with the labels that each got.

#183 reduce number of retries for guest policy operations
  policies/policies.go
Labels: approved, lgtm, size/XS

#184 Ignore unknown fields when unmarshalling state file
  agentendpoint/patch_task.go
  agentendpoint/patch_task_beta.go
Labels: approved, lgtm, size/XS

#185 add timeout to watchconfig
  config/config.go
  main.go
Labels: approved, lgtm, size/XS

#186 fix watchconfig bug
  agentendpoint/agentendpoint.go
  config/config.go
Labels: approved, lgtm, size/XS

#188 fix excludes and exclusive-includes for apt, yum and zypper
  agentendpoint/patch_beta_linux.go
  agentendpoint/patch_linux.go
Labels: approved, lgtm, size/S

#187 Add RegisterAgent rpcs, update libraries, update error handling
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/agentendpoint_beta_test.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task_beta_test.go
  agentendpoint/exec_task_test.go
  config/config.go
  go.mod
  go.sum
  policies/local.go
Labels: approved, lgtm, size/L

#189 switch default service endpoint
  config/config.go
  config/config_test.go
  go.mod
Labels: approved, lgtm, size/S

#190 Fix state marshal/unmarshal, drop unused 'beta' code
  OWNERS
  agentendpoint/agentendpoint_beta.go
  agentendpoint/agentendpoint_beta_test.go
  agentendpoint/exec_task_beta.go
  agentendpoint/exec_task_beta_test.go
  agentendpoint/patch_beta_linux.go
  agentendpoint/patch_beta_windows.go
  agentendpoint/patch_task.go
  agentendpoint/patch_task_beta.go
  agentendpoint/task_state_beta.go
  agentendpoint/task_state_beta_test.go
  agentendpoint/task_state_test.go
  go.mod
  go.sum
  policies/OWNERS
  policies/local.go
  policies/local_test.go
  util/util.go
Labels: approved, lgtm, size/XXL

#193 e2e_tests: make sure retry calls log to testlog
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/main.go
Labels: approved, lgtm, size/L

#194 Call RegisterAgent at start and then once every 24 hours
  agentendpoint/agentendpoint.go
  main.go
Labels: approved, lgtm, size/S

#195 Don't set service endpoint by default in e2e_tests
  e2e_tests/config/config.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XS

#196 Fix service endpoint config in e2e_tests
  e2e_tests/gcp_clients/gcp_clients.go
Labels: approved, lgtm, size/XS

#181 Add source field in googet spec.
  packaging/googet/google-osconfig-agent.goospec
Labels: approved, lgtm, ok-to-test, size/XS

#197 Separate agent endpoint and service endpoint in e2e_tests
  e2e_tests/config/config.go
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#198 Add alpha client libraries
  go.mod
  go.sum
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/agent_endpoint_client.go
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/agent_endpoint_client_example_test.go
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/doc.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/agentendpoint.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/guest_policies.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/inventory.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/patch_jobs.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
Labels: approved, lgtm, size/XXL

#199 Move to v1alpha1 client, add ReportInventory client method
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/task_state_test.go
Labels: approved, lgtm, size/M
