Repository GoogleCloudPlatform/osconfig, pull requests merged in 2021-08, with the labels that each got.

#371 Support Windows Application Inventory
  agentendpoint/inventory.go
  go.sum
  packages/packages.go
  packages/packages_windows.go
  packages/windows_application_windows.go
Labels: size/L, approved, lgtm, ok-to-test

#378 Update Terraform scripts for multi-project deployments tutorial.
  examples/Terraform/multi-project-deployments/README.md
  examples/Terraform/multi-project-deployments/auth/README.md
  examples/Terraform/multi-project-deployments/auth/TerraformDeployer.yaml
  examples/Terraform/multi-project-deployments/auth/VM_Manager_Deployer.yaml
  examples/Terraform/multi-project-deployments/create_guest_policies/terraform.example.tfvars
  examples/Terraform/multi-project-deployments/create_guest_policies/terraform.tfvars
  examples/Terraform/multi-project-deployments/create_patch_deployments/terraform.example.tfvars
  examples/Terraform/multi-project-deployments/create_patch_deployments/terraform.tfvars
  examples/Terraform/multi-project-deployments/create_projects/main.tf
  examples/Terraform/multi-project-deployments/create_projects/terraform.tfvars
  examples/Terraform/multi-project-deployments/create_projects/variables.tf
  examples/Terraform/multi-project-deployments/create_projects/versions.tf
  examples/Terraform/multi-project-deployments/create_vm_instances/README.md
  examples/Terraform/multi-project-deployments/create_vm_instances/main.tf
  examples/Terraform/multi-project-deployments/create_vm_instances/outputs.tf
  examples/Terraform/multi-project-deployments/create_vm_instances/terraform.example.tfvars
  examples/Terraform/multi-project-deployments/create_vm_instances/variables.tf
  examples/Terraform/multi-project-deployments/create_vm_instances/versions.tf
  examples/Terraform/multi-project-deployments/enable_projects_for_vmmanager/README.md
  examples/Terraform/multi-project-deployments/enable_projects_for_vmmanager/main.tf
  examples/Terraform/multi-project-deployments/enable_projects_for_vmmanager/outputs.tf
  examples/Terraform/multi-project-deployments/enable_projects_for_vmmanager/variables.tf
  examples/Terraform/multi-project-deployments/enable_projects_for_vmmanager/versions.tf
  examples/Terraform/multi-project-deployments/preparation_scripts/create_terraform_custom_role.sh
  examples/Terraform/multi-project-deployments/preparation_scripts/create_terraform_service_account.sh
  examples/Terraform/multi-project-deployments/preparation_scripts/create_tf_admin_project.sh
  examples/Terraform/multi-project-deployments/preparation_scripts/enable_services_in_admin_project.sh
  examples/Terraform/multi-project-deployments/preparation_scripts/setup_env.sh
Labels: size/XL, approved, lgtm, needs-ok-to-test

#377 Return lower-case package name
  packages/apt_deb.go
Labels: size/XS, approved, lgtm, ok-to-test
