Repository GoogleCloudPlatform/osconfig, pull requests merged in 2021-04, with the labels that each got.

#304 Add helpful error log if a service account is missing
  retryutil/retry.go
Labels: approved, lgtm, size/XS

#302 e2e_tests: add OSPolicies tests for package install
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1alpha/doc.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1alpha/gapic_metadata.json
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1alpha/os_config_zonal_client.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/config_common.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/instance_os_policies_compliance.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/inventory.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy_assignments.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_common.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_zonal_service.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/vulnerability.pb.go
  e2e_tests/main.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XXL

#303 Gather inventory 3-5min after agent start
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  main.go
Labels: approved, lgtm, size/M

#305 Do not enforce repo_gpgcheck in guestpolicies
  e2e_tests/utils/utils.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: approved, lgtm, size/S

#306 e2e_tests: Add more OSPolicies package and repo tests
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/L

#307 Disable OSPolicies by default since it is an unreleased feature
  agentconfig/agentconfig.go
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_test.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/M

#308 Fix e2e_tests
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#309 Fix e2e_test typo
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XS

#310 Add task_type context logging
  agentendpoint/agentendpoint.go
Labels: approved, lgtm, size/XS

#311 e2e_test: add tests for FileResource
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Labels: approved, lgtm, size/L

#312 Change metadata http client to ignore http proxies
  agentconfig/agentconfig.go
Labels: approved, lgtm, size/S

#313 Fix bugs/add more logging for OSPolicies
  agentendpoint/config_task.go
  config/file_resource.go
Labels: approved, lgtm, size/S

#315 PackageResource: make sure to run AptUpdate prior to package install
  config/package_resource.go
  config/package_resource_test.go
Labels: approved, lgtm, size/M

#314 e2e_tests: check InstanceOSPoliciesCompliance for each test case, add LocalPath FileResource test
  e2e_tests/go.mod
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/test_suites/patch/test_setup.go
Labels: approved, lgtm, size/L

#299 Set custom user agent
  agentconfig/agentconfig.go
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/S

#317 Config task: only run post check on resources that have already been evaluated
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
Labels: approved, lgtm, size/M

#318 ExecResource: make sure we set permissions correctly for downloaded files
  config/exec_resource.go
  config/file.go
  config/file_resource.go
  config/package_resource.go
  util/util.go
Labels: approved, lgtm, size/S

#319 e2e_tests: add ExecResource tests
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/XL

#320 e2e_tests: move to using inventory api for inventory reporting
  e2e_tests/compute/instance.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Labels: approved, lgtm, size/M

#321 Add top level directories for os policy examples
  examples/OSPolicyAssignments/README.md
  examples/OSPolicyAssignments/install_package/console/os_policy.yaml
  examples/OSPolicyAssignments/install_package/gcloud/os_policy_assignment.yaml
Labels: approved, lgtm, size/XS

#323 e2e_tests: fix windows package and repository tests
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Labels: approved, lgtm, size/S

#322 Only report installed packages for dpkg
  agentendpoint/config_task.go
  config/package_resource.go
  main.go
  packages/apt_deb.go
  packages/apt_deb_test.go
Labels: approved, lgtm, size/S

#324 e2e_tests: reduce size of instances, use pd-balanced, rerun failed tests once
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/patch/test_setup.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/L

#325 Add CONFIG_V1 capability
  agentconfig/agentconfig.go
Labels: approved, lgtm, size/XS

#326 Make sure we use the same test name for reruns
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XS

#327 e2e_tests: Move api from an internal directory
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/doc.go
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/gapic_metadata.json
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/os_config_zonal_client.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/config_common.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/instance_os_policies_compliance.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/inventory.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy_assignments.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_common.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_zonal_service.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/vulnerability.pb.go
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: approved, lgtm, size/S

#328 Create top level directories for gcloud and console for os policy assignment examples
  examples/OSPolicyAssignments/console/README.md
  examples/OSPolicyAssignments/console/install_package.yaml
  examples/OSPolicyAssignments/gcloud/README.md
  examples/OSPolicyAssignments/gcloud/install_package.yaml
Labels: approved, lgtm, size/XS

#329 e2e_test: Add timouts to OSPolicy tests so we don't wait forever
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XS

#330 e2e_tests: Add additional logging for OSPolicy errors.
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/S

#333 e2e_tests: Add test cases of installing dbe, rpm and msi packages
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Labels: approved, lgtm, size/L

#332 Fix panic when installing MSI
  config/package_resource.go
Labels: approved, lgtm, size/XS

#335 e2e_tests: increase the deadline for OSPolicy tests and only start after a zone has been secured
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XS

#334 Examples for os policy assignments
  examples/OSPolicyAssignments/console/exec_script_linux_all.yaml
  examples/OSPolicyAssignments/console/install_msi_windows_all.yaml
  examples/OSPolicyAssignments/console/install_package.yaml
  examples/OSPolicyAssignments/console/setup_repo_and_install_package_linux_yum.yaml
  examples/OSPolicyAssignments/gcloud/exec_script_linux_all.yaml
  examples/OSPolicyAssignments/gcloud/filter_vms_by_labels_windows_all.yaml
  examples/OSPolicyAssignments/gcloud/filter_vms_by_os_family_linux_rhel_centos.yaml
  examples/OSPolicyAssignments/gcloud/install_msi_windows_all.yaml
  examples/OSPolicyAssignments/gcloud/install_package.yaml
  examples/OSPolicyAssignments/gcloud/setup_repo_and_install_package_linux_yum.yaml
Labels: approved, lgtm, size/L

#336 e2e_tests: Don't retry failed OSPolicy tests, fix msi test
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: approved, lgtm, size/M

#337 e2e_tests: unlock mutex for CreateOSPolicyAssignment as soon as create finishes
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XS

#338 e2e_tests: fixup OSPolicy tests, start testing in staging
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#340 Remove pre-release flag from config
  agentconfig/agentconfig.go
  agentendpoint/agentendpoint.go
  config/repository_resource.go
  config/repository_resource_test.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/M

#339 e2e_tests: Fix a few SUSE tests
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Labels: approved, lgtm, size/S

#341 Set minWaitDuration as a string instead of object
  examples/OSPolicyAssignments/gcloud/exec_script_linux_all.yaml
  examples/OSPolicyAssignments/gcloud/filter_vms_by_labels_windows_all.yaml
  examples/OSPolicyAssignments/gcloud/filter_vms_by_os_family_linux_rhel_centos.yaml
  examples/OSPolicyAssignments/gcloud/install_msi_windows_all.yaml
  examples/OSPolicyAssignments/gcloud/setup_repo_and_install_package_linux_yum.yaml
Labels: approved, lgtm, size/S

#342 e2e_tests: re-add retries to OSPolicies
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/M

#344 e2e_tests: add validation mode tests
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: approved, lgtm, size/M

#345 ConfigTask: add additional info logs
  agentendpoint/config_task.go
  config/exec_resource.go
Labels: approved, lgtm, size/S

#346 Align start and end task logs
  agentendpoint/config_task.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/patch_task.go
Labels: approved, lgtm, size/M

#347 e2e_tests: enable stable tests for OSPolicies
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XS
