Repository GoogleCloudPlatform/osconfig, pull requests merged in 2021-01, with the labels that each got.

#273 Update protos, merge from master, add config error test cases
  agentconfig/agentconfig.go
  agentconfig/agentconfig_test.go
  agentendpoint/agentendpoint.go
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/task_state.go
  agentendpoint/task_state_test.go
  config/config.go
  config/exec_resource.go
  config/file.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/package_resource_test.go
  config/repository_resource.go
  config/repository_resource_test.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/utils/utils.go
  go.mod
  go.sum
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/agent_endpoint_client.go
  internal/cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1/doc.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/agentendpoint.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/config_common.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/guest_policies.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/inventory.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/os_policy.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/patch_jobs.pb.go
  internal/google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1/tasks.pb.go
  main.go
  ospatch/updates_windows.go
  ospatch/yum_update_test.go
  packages/yum.go
Labels: approved, lgtm, size/XXL

#274 Fix builds for ppc and s390x
  packages/cos.go
  packages/cos_stub.go
  packages/cos_test.go
Labels: approved, lgtm, size/M

#275 Add policy state recording
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
Labels: approved, lgtm, size/M

#276 Ensure package cache gets reset on enforce
  config/package_resource.go
  config/package_resource_test.go
Labels: approved, lgtm, size/M

#280 Simplify build tags for COS package
  packages/cos.go
  packages/cos_stub.go
  packages/cos_test.go
Labels: approved, lgtm, size/S

#281 update apt package lists before running installs
  go.mod
  go.sum
  packages/apt_deb.go
  policies/apt.go
Labels: approved, lgtm, size/M

#282 update reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#283 Make writes atomic, add unused "allowDowngrades" option to apt, fix a few recipe issues
  main_linux.go
  packages/apt_deb.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/steps.go
  util/util.go
Labels: approved, lgtm, size/L

#284 Ensure we cleanup on error in AtomicWrite
  util/util.go
Labels: approved, lgtm, size/S
