Repository GoogleCloudPlatform/osconfig, pull requests merged in 2021-06, with the labels that each got.

#354 e2e_tests: add tests for ExecResource output
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/gapic_metadata.json
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/os_config_zonal_client.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/config_common.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/instance_os_policies_compliance.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/inventory.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy_assignments.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_common.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_zonal_service.pb.go
  e2e_tests/api/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/vulnerability.pb.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: approved, lgtm, size/XXL

#355 Agent efficiency improvements/bugfixes/logging updates
  agentconfig/agentconfig.go
  agentendpoint/agentendpoint.go
  agentendpoint/config_task.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  attributes/attributes_test.go
  clog/clog.go
  config/package_resource.go
  inventory/inventory.go
  main.go
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/updates.go
  ospatch/updates_test.go
  ospatch/yum_update.go
  ospatch/zypper_patch.go
  ospatch/zypper_patch_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/cos.go
  packages/cos_test.go
  packages/gem.go
  packages/googet.go
  packages/googet_test.go
  packages/packages.go
  packages/packages_linux.go
  packages/packages_windows.go
  packages/pip.go
  packages/qfe_windows.go
  packages/rpm.go
  packages/rpm_test.go
  packages/yum.go
  packages/yum_test.go
  packages/zypper.go
  packages/zypper_test.go
  policies/apt.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/yum.go
  policies/zypper.go
  tasker/tasker.go
Labels: approved, lgtm, size/XL

#356 Create win-validation-powershell.yaml
  examples/OSPolicyAssignments/console/win-validation-powershell.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#357 Fix build on some architectures
  packages/cos_stub.go
Labels: approved, lgtm, size/XS

#359 e2e_tests: point to official osconfig client library
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/doc.go
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/gapic_metadata.json
  e2e_tests/api/cloud.google.com/go/osconfig/apiv1alpha/os_config_zonal_client.go
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/test_suites/ospolicies/ospolicies.go
Labels: approved, lgtm, size/XXL

#362 Use exec.CommandContext so that canceling the context also kills any running processes
  config/exec_resource.go
  config/package_resource_test.go
  ospatch/yum_update_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/gem.go
  packages/googet_test.go
  packages/packages.go
  packages/qfe_windows.go
  packages/rpm_test.go
  packages/yum.go
  packages/yum_test.go
  packages/zypper.go
  packages/zypper_test.go
  util/util.go
Labels: approved, lgtm, size/L

#363 chore: Fixing a comment.
  examples/OSPolicyAssignments/console/setup_repo_and_install_package_linux_apt.yaml
Labels: approved, lgtm, size/XS

#364 Add CloudOps examples for CentOS
  examples/OSPolicyAssignments/console/cloudops-centos7.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M
