Repository GoogleCloudPlatform/osconfig, pull requests merged in 2021-09, with the labels that each got.

#382 Add more info logs, actually cleanup unmanaged repos
  agentconfig/agentconfig.go
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/patch_windows.go
  agentendpoint/reboot_windows.go
  config/exec_resource.go
  config/file_resource.go
  config/repository_resource.go
  ospatch/system_linux.go
  ospatch/system_test_stub.go
  ospatch/system_windows.go
  ospatch/updates_linux.go
  ospatch/updates_test_stub.go
  ospatch/updates_windows.go
  packages/cos.go
  packages/cos_stub.go
  packages/cos_test.go
  packages/stub_linux.go
  packages/stub_windows.go
  policies/recipes/steps_linux.go
  policies/recipes/steps_windows.go
Labels: size/L, approved, lgtm

#383 Add centos stream rocky linux and available package tests
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/utils/utils.go
Labels: size/L, approved, lgtm

#384 Fix rpm/deb package formating for inventory reporting
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
Labels: size/L, approved, lgtm

#385 Deprecate old config directory in favor of new cache directory
  agentconfig/agentconfig.go
  agentendpoint/agentendpoint.go
  agentendpoint/task_state.go
  agentendpoint/task_state_test.go
  go.mod
  go.sum
  main.go
  packaging/debian/postrm
  packaging/debian/rules
  packaging/google-osconfig-agent.spec
Labels: size/L, approved, lgtm

#386 ReportInventory: Fix bug in deb/rpm inventory, reduce calls to append
  agentconfig/agentconfig.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
Labels: size/L, approved, lgtm

#387 Correctly check for folder existance in package upgrade
  packaging/debian/postrm
  packaging/google-osconfig-agent.spec
Labels: size/XS, approved, lgtm

#388 Fix some e2e test failures
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#390 e2e_tests: fix a test output mismatch
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: size/XS, approved, lgtm

#389 Fixed the runWithPty function to set ctty to child's filedesc
  packages/pty_linux.go
Labels: approved, lgtm, size/S

#391 Config: Add package info caching
  agentconfig/agentconfig.go
  config/package_resource.go
  config/package_resource_test.go
  packages/msi_windows.go
  packages/stub_linux.go
Labels: size/L, approved, lgtm
