Repository GoogleCloudPlatform/osconfig, pull requests merged in 2021-07, with the labels that each got.

#365 Fix bug in printing packages to update, return error for zypper patch
  ospatch/apt_upgrade.go
  ospatch/googet_update.go
  ospatch/yum_update.go
  ospatch/zypper_patch.go
  packages/packages.go
Labels: approved, lgtm, size/S

#366 Add examples/Terraform directory.
  examples/Terraform/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#369 Skip getting patch info when no patches are found.
  packages/zypper.go
  packages/zypper_test.go
Labels: approved, lgtm, size/S

#370 Update Zypper patch info parsing
  packages/zypper.go
  packages/zypper_test.go
Labels: approved, lgtm, size/XS

#368 Create OWNERS file for examples directory
  examples/OWNERS
Labels: approved, lgtm, size/S

#372 e2e_tests: move to manually generated osconfig library
  e2e_tests/gcp_clients/gcp_clients.go
  e2e_tests/go.mod
  e2e_tests/go.sum
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1alpha/doc.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1alpha/gapic_metadata.json
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1alpha/os_config_zonal_client.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/config_common.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/instance_os_policies_compliance.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/inventory.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/os_policy_assignments.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_common.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/osconfig_zonal_service.pb.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha/vulnerability.pb.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: approved, lgtm, size/XXL

#373 Send basic inventory with RegisterAgent
  agentendpoint/agentendpoint.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L
