Repository GoogleCloudPlatform/osconfig, pull requests merged in 2022-02, with the labels that each got.

#413 Add DisableLocalLogging option
  agentconfig/agentconfig.go
  main.go
Labels: approved, lgtm, size/S

#415 Add regex support to package exclusion in OS Patch
  agentendpoint/patch_linux.go
  agentendpoint/patch_linux_test.go
  e2e_tests/test_suites/patch/patch.go
  ospatch/apt_upgrade.go
  ospatch/exclude.go
  ospatch/googet_update.go
  ospatch/updates.go
  ospatch/updates_test.go
  ospatch/yum_update.go
  ospatch/zypper_patch.go
  ospatch/zypper_patch_test.go
  packages/yum.go
  packages/yum_test.go
Labels: size/L, approved, lgtm, ok-to-test

#416 Create change_group.yaml
  examples/OSPolicyAssignments/gcloud/change_group.yaml
Labels: approved, lgtm, size/S

#419 e2e_tests: update OS targets, adjust retries
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/utils/utils.go
Labels: size/L, approved, lgtm

#420 Create e2e test that runs apt-get in a state that makes it downgrade a package
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/test_suites/patch/test_setup.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#418 Add --allow-downgrades flag to apt-get calls
  packages/apt_deb.go
  packages/apt_deb_test.go
Labels: approved, lgtm, size/M

#421 e2e_tests: fix patch test rerun
  e2e_tests/test_suites/patch/patch.go
Labels: approved, lgtm, size/S

#422 Fix string that apt-get returns when requiring downgrade
  packages/apt_deb.go
  packages/apt_deb_test.go
Labels: size/XS, approved, lgtm

#423 Update the error message when an exec task is run on Windows without an interpreter specified
  agentendpoint/exec_task.go
Labels: size/XS, approved, lgtm
