Repository GoogleCloudPlatform/osconfig, pull requests merged in 2023-11, with the labels that each got.

#496 Removing deprecated Win for containers OSs
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#497 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#499 Increasing test timeouts
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/inventory/inventory.go
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/patch/patch.go
  e2e_tests/test_suites/patch/test_setup.go
Labels: approved, lgtm, size/M

#498 Update owners.
  OWNERS
Labels: approved, size/S

#500 Removing obsolete MS Windows 2019 images
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#481 Call fqdn
  agentconfig/agentconfig.go
  agentconfig/agentconfig_test.go
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#501 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#504 Added SCODE to Windows error description
  main.go
  main_linux.go
  main_windows.go
  ospatch/updates_windows.go
  packages/wua_windows.go
Labels: approved, lgtm, size/M, ok-to-test

#503 docs(osconfig):add OS policy example for CIS scanning
  examples/OSPolicyAssignments/CIS/cis-level1-once-a-day-policy.yaml
Labels: approved, lgtm, size/M

#505 Added ekrementeskii and MahmoudNada0 to OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, ok-to-test

#509 Adds three more OS Policy examples to CIS folder
  examples/OSPolicyAssignments/CIS/cis-exclude-check-once-a-day.yaml
  examples/OSPolicyAssignments/CIS/cis-level1-once-an-hour-policy.yaml
  examples/OSPolicyAssignments/CIS/cis-level2-once-a-day-policy.yaml
Labels: size/L, approved, lgtm

#508 Updating owners
  examples/OWNERS
Labels: approved, lgtm, size/S

#517 Update feature names in the README file
  README.md
Labels: size/XS, approved, lgtm

#502 Fix parse yum updates to consider the packages under 'installing dependencies' keyword
  packages/yum.go
  packages/yum_test.go
Labels: approved, lgtm, size/M

#518 Some change to create an agent release
  README.md
Labels: size/XS, approved, lgtm
