Repository GoogleCloudPlatform/osconfig, pull requests merged in 2023-03, with the labels that each got.

#462 Remove old images from e2e tests image list
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#457 Fix comparing exec.Cmd in mock on Go1.20
  config/package_resource_test.go
  ospatch/yum_update_test.go
  packages/apt_deb_test.go
  packages/googet_test.go
  packages/rpm_test.go
  packages/yum_test.go
  packages/zypper_test.go
  util/mocks/match.go
Labels: size/L, approved, ok-to-test

#469 support new format of zypper patch
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1/doc.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1/os_config_client.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1/os_config_zonal_client.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1/os_policy_assignments.pb.go
  osinfo/osinfo_linux_test.go
  packages/msi_windows.go
  packages/zypper.go
  packages/zypper_test.go
  policies/local_test.go
Labels: size/L, approved, lgtm

#470 Revert "Call FQDN"
  agentconfig/agentconfig.go
  agentconfig/agentconfig_test.go
Labels: size/XS, approved, lgtm
