Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-05, with the labels that each got.

#554 Update go.mod
  go.mod
Labels: size/XS, approved, lgtm

#556 Updating dependencies and respective checksums
  go.mod
  go.sum
Labels: size/XL, approved, lgtm, dependencies

#557 Logrus dependency update
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#558 Use signed-by keyring approach for apt repos in Debian 12+ and Ubuntu 24+
  policies/apt.go
  policies/apt_test.go
Labels: approved, lgtm, size/M

#559 Fix Debian-12 package build workflow typo
  packagebuild/workflows/build_deb12.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
Labels: size/XS, approved, lgtm

#560 Initial config of dependabot for the dependency updates scanning
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#561 Revert "Initial config of dependabot for the dependency updates scanning"
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#562 Dependabot dependency updates
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#568 Update Debian-12 package build workflow to use debian-cloud project
  packagebuild/workflows/build_deb12.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
Labels: size/XS, approved, lgtm

#569 Adding advanced CodeQL settings to scan on PRs
  .github/workflows/codeql.yml
Labels: approved, lgtm, size/M

#570 Using the default reviewer set for PR approvals
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#582 Add a temporary e2e test image for Ubuntu to test the latest osconfig-agent stable version
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#583 E2e tests: install gnupg2 and run apt update in VMs startup-scripts
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#486 Write inventory to attributes only if enabled
  agentconfig/agentconfig.go
  agentendpoint/inventory.go
Labels: approved, lgtm, size/S

#576 Remove dependabot not needed label
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#586 Fix for lock location
  agentconfig/agentconfig.go
  main_windows.go
Labels: approved, lgtm, size/S

#587 E2e tests: use family url format instead of specific version url for head test images
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#590 E2e tests: Fix EL version detection logic in E2E tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#592 E2e tests: allow passing spesific EL version number to InstallOSConfigEL func
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#603 rollback masive dependency update
  go.mod
  go.sum
Labels: size/XL, approved, lgtm

#604 update go-cmp dependency
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#613 bump golang.org/x/crypto version
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#612 Update Apt e2e tests to pull osconfig-agent pkg from new AR repos instead of rapture
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
  e2e_tests/test_suites/patch/test_setup.go
  e2e_tests/utils/utils.go
Labels: size/L, approved, lgtm

#611 Update to the CIS OS policy samples
  examples/OSPolicyAssignments/console/CIS/cis-exclude-check-once-a-day.yaml
  examples/OSPolicyAssignments/console/CIS/cis-level1-once-an-hour-policy.yaml
  examples/OSPolicyAssignments/console/CIS/cis-level2-once-a-day-policy.yaml
Labels: approved, lgtm, size/S

#614 Allow Apt & Yum e2e tests to pull osconfig-agent pkg from testing repos
  e2e_tests/utils/utils.go
Labels: size/L, approved, lgtm

#615 fix SUSE e2e tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#616 Allow Windows e2e tests to pull osconfig-agent pkg from testing (private) repos from Artifact registry
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S
