Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-04, with the labels that each got.

#538 Bump output size limit to 500KB
  config/exec_resource.go
Labels: size/XS, approved, lgtm

#541 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, do-not-merge/invalid-owners-file

#548 Removed debian-10 from e2e tests
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#544 OS Config windows state file location changed
  agentconfig/agentconfig.go
Labels: approved, lgtm, size/S

#545 Copy packagebuild folder from guest-test-infra repo to osconfig repo
  packagebuild/README.md
  packagebuild/common.sh
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_goo.sh
  packagebuild/daisy_startupscript_rpm.sh
  packagebuild/test_build.sh
  packagebuild/workflows/build_deb10.wf.json
  packagebuild/workflows/build_deb11.wf.json
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb12.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
  packagebuild/workflows/build_el6.wf.json
  packagebuild/workflows/build_el7.wf.json
  packagebuild/workflows/build_el8.wf.json
  packagebuild/workflows/build_el8_arm64.wf.json
  packagebuild/workflows/build_el9.wf.json
  packagebuild/workflows/build_el9_arm64.wf.json
  packagebuild/workflows/build_goo.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: approved, lgtm, size/XXL

#549 Disabled some images which are either past EoL or broken
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#552 Fix e2e tests for exec-output size limit
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: approved, lgtm, size/S

#553 Remove SBOM generation logic from package build workflows
  packagebuild/README.md
  packagebuild/common.sh
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_goo.sh
  packagebuild/daisy_startupscript_rpm.sh
  packagebuild/workflows/build_deb10.wf.json
  packagebuild/workflows/build_deb11.wf.json
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb12.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
  packagebuild/workflows/build_el6.wf.json
  packagebuild/workflows/build_el7.wf.json
  packagebuild/workflows/build_el8.wf.json
  packagebuild/workflows/build_el8_arm64.wf.json
  packagebuild/workflows/build_el9.wf.json
  packagebuild/workflows/build_el9_arm64.wf.json
  packagebuild/workflows/build_goo.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: size/L, approved, lgtm
