Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-03, with the labels that each got.

#533 Adds a console and gcloud example policies
  examples/OSPolicyAssignments/console/google-cloud-sap-agent.yaml
  examples/OSPolicyAssignments/gcloud/google_cloud_sap_agent.yaml
Labels: size/XL, approved, lgtm, needs-ok-to-test

#534 Update OWNERS file to replace mahmoudn GitHub username by personal email GitHub username
  OWNERS
Labels: size/XS, approved, lgtm

#537 Enable OSConfig agent to read GPG keys files with multiple entities
  config/repository_resource.go
  config/repository_resource_test.go
  policies/apt.go
  policies/apt_test.go
Labels: size/L, approved, lgtm
