Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-09, with the labels that each got.

#659 Revert "update osconfig api to v1.13.0 & indirect dependency update"
  go.mod
  go.sum
  packagebuild/workflows/build_deb11_arm64.wf.json
Labels: size/L, approved, lgtm

#662 Move packagebuild presubmit to osconfig
  presubmit_packagebuild/Dockerfile
  presubmit_packagebuild/main.sh
Labels: size/L, approved, lgtm

#664 Update grpc library and other dependencies.
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#665 Revert "Update grpc library and other dependencies."
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#666 bump version of the gRPC
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#667 Revert "bump version of the gRPC"
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#669 Set new version of gRPC for test
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#671 Implement keepalive config
  agentendpoint/agentendpoint.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#672 Upgrade grpc and it's dependencies to latest version
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#676 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#673 Revert back Source package info delivery to control-plane
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/task_state_test.go
  config/config.go
  config/exec_resource.go
  config/exec_resource_test.go
  config/file.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/package_resource_test.go
  config/repository_resource.go
  config/repository_resource_test.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1/os_config_zonal_client.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1/osconfig_zonal_service.pb.go
  e2e_tests/osconfig_server/osconfig_data_builder.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/patch/patch.go
  go.mod
  go.sum
  policies/apt.go
  policies/apt_test.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/googet_test.go
  policies/local.go
  policies/local_test.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: size/L, approved, lgtm

#677 Aggregate Dependabot changes to go.mod
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#683 another batch of depencies upgrade
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#684 Revert "Bump go.opentelemetry.io/otel from 1.24.0 to 1.30.0"
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#690 Third batch of dependencies upgrade
  go.mod
  go.sum
Labels: size/L, approved, lgtm
