Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-08, with the labels that each got.

#649 Fix Debian-12 failing test by using gcsfuse pkg & Fix fetching gpg key unit tests
  config/repository_resource_test.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/utils/utils.go
  policies/apt_test.go
Labels: approved, lgtm, size/M

#650 Disable Repository Resource test for SLES-12
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: size/XS, approved, lgtm

#652 Replace osconfig-agent-test pkg by gcsfuse in ospolicies tests and inventory-report tests
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: size/L, approved, lgtm

#653 Use gcsfuse pkg in guest-policies e2e in pkg update tests instead of old pkgs
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: approved, lgtm, size/M

#655 Fix golang version format to fix builds.
  go.mod
Labels: size/XS, approved, lgtm

#656 Revert "Source package info delivery to control-plane"
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/task_state_test.go
  config/config.go
  config/exec_resource.go
  config/exec_resource_test.go
  config/file.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/package_resource_test.go
  config/repository_resource.go
  config/repository_resource_test.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1/os_config_zonal_client.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1/osconfig_zonal_service.pb.go
  e2e_tests/osconfig_server/osconfig_data_builder.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/patch/patch.go
  policies/apt.go
  policies/apt_test.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/googet_test.go
  policies/local.go
  policies/local_test.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: size/L, approved, lgtm
