Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-06, with the labels that each got.

#617 Disable centos-stream-8 tests as it reached EOL in May 31
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#618 Fix the logic of pick region for Artifact Registry function
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#619 Disable SUSE tests to run with testing agent repo
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#621 Update e2e tests to use VMM team's GCP project for pkgs testing version
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm

#622 Extract source name and version for dpkg packages.
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/cos_test.go
  packages/googet_test.go
  packages/packages.go
  packages/rpm_test.go
  packages/yum_test.go
  packages/zypper_test.go
Labels: size/XL, approved, lgtm

#623 Fix(dpkg) return onlt installed items as inventory
  packages/apt_deb.go
  packages/apt_deb_test.go
Labels: approved, lgtm, size/S

#625 update README.md file
  README.md
Labels: size/XS, approved, lgtm

#624 Extract source_name(source_rpm) for rpm packages
  config/package_resource_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/packages.go
  packages/packages_test.go
  packages/rpm.go
  packages/rpm_test.go
Labels: size/XL, approved, lgtm

#626 Adding Architecture to the packages being installed/updated in yum repo
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  attributes/attributes_test.go
  config/package_resource_test.go
  ospatch/yum_update.go
  ospatch/yum_update_test.go
  ospatch/zypper_patch_test.go
  packages/apt_deb.go
  packages/apt_deb_test.go
  packages/cos.go
  packages/cos_test.go
  packages/gem.go
  packages/googet.go
  packages/googet_test.go
  packages/packages.go
  packages/pip.go
  packages/rpm_test.go
  packages/yum.go
  packages/yum_test.go
  packages/zypper.go
  packages/zypper_test.go
Labels: size/L, approved, lgtm

#627 Update old SLES images urls
  e2e_tests/utils/utils.go
Labels: size/XS, approved, lgtm
