Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-01, with the labels that each got.

#526 Update cis-exclude-check-once-a-day.yaml
  examples/OSPolicyAssignments/console/CIS/cis-exclude-check-once-a-day.yaml
Labels: size/XS, approved, lgtm

#527 Fix SUSE package update e2e tests to use another existing package
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: size/XS, approved, lgtm

#528 Fix zypper patch info parser to consider conflicts-pkgs float versions
  packages/zypper.go
  packages/zypper_test.go
Labels: size/L, approved, lgtm

#529 Fix SUSE pkg-update and pkg-no-update e2e tests
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: approved, lgtm, size/S

#530 Fix Enterprise Linux Recipe-Steps tests to install info dependency package in the startup-script
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: size/XS, approved, lgtm
