Repository GoogleCloudPlatform/osconfig, pull requests merged in 2024-07, with the labels that each got.

#631 Pipeline testing 00
  packagebuild/README.md
Labels: size/XS, approved, lgtm

#634 Remove RHEL-7 and CentOS-7 images from e2e tests
  e2e_tests/test_suites/inventory/test_setup.go
  e2e_tests/test_suites/inventoryreporting/test_setup.go
  e2e_tests/test_suites/patch/test_setup.go
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/M

#635 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#636 Updating Windows & Linux Chrome packages to fix failing e2e tests.
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Labels: size/XS, approved, lgtm

#637 update osconfig api to v1.13.0 & indirect dependency update
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#638 Enable gpgcheck flag for RPM e2e tests
  e2e_tests/utils/utils.go
Labels: approved, lgtm, size/S

#639 Source package info delivery to control-plane
  agentendpoint/agentendpoint.go
  agentendpoint/agentendpoint_beta.go
  agentendpoint/agentendpoint_test.go
  agentendpoint/config_task.go
  agentendpoint/config_task_test.go
  agentendpoint/exec_task.go
  agentendpoint/exec_task_test.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
  agentendpoint/patch_linux.go
  agentendpoint/patch_task.go
  agentendpoint/patch_windows.go
  agentendpoint/task_state_test.go
  config/config.go
  config/exec_resource.go
  config/exec_resource_test.go
  config/file.go
  config/file_resource.go
  config/file_resource_test.go
  config/package_resource.go
  config/package_resource_test.go
  config/repository_resource.go
  config/repository_resource_test.go
  e2e_tests/internal/cloud.google.com/go/osconfig/apiv1/os_config_zonal_client.go
  e2e_tests/internal/google.golang.org/genproto/googleapis/cloud/osconfig/v1/osconfig_zonal_service.pb.go
  e2e_tests/osconfig_server/osconfig_data_builder.go
  e2e_tests/test_suites/guestpolicies/guest_policies.go
  e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
  e2e_tests/test_suites/patch/patch.go
  policies/apt.go
  policies/apt_test.go
  policies/changes.go
  policies/changes_test.go
  policies/googet.go
  policies/googet_test.go
  policies/local.go
  policies/local_test.go
  policies/policies.go
  policies/recipes/artifacts.go
  policies/recipes/installrecipe.go
  policies/recipes/steps.go
  policies/yum.go
  policies/yum_test.go
  policies/zypper.go
  policies/zypper_test.go
Labels: size/L, approved, lgtm

#643 Fix GuestPolicies e2e tests for SLES-15 SP5 by removing zypper update from VMs startup script
  e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Labels: size/XS, approved, lgtm

#644 Fix OSPolicies e2e tests for SLES-15 SP5 by removing zypper update from VMs startup script
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Labels: size/XS, approved, lgtm

#645 Fix SLES-12 SP5 RPM package-resource e2e test
  e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
  e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Labels: size/XS, approved, lgtm

#646 Add debugging logs for repository resource config
  config/file_resource.go
  config/file_resource_test.go
  config/repository_resource.go
  config/repository_resource_test.go
  packages/zypper.go
Labels: approved, lgtm, size/S

#648 Fix for old state file on Windows
  agentconfig/agentconfig.go
  agentendpoint/task_state.go
Labels: approved, lgtm, size/S
