Repository GoogleCloudPlatform/osconfig, pull requests merged in 2025-05, with the labels that each got.

#814 Improve packages package coverage
  packages/packages_test.go
  packages/pip_test.go
  packages/testdata/linux-pip-list-format-json.expected
  packages/testdata/linux-pip-list-format-json.stdout
  packages/testdata/linux-pip-list-outdated-format-json.expected
  packages/testdata/linux-pip-list-outdated-format-json.stdout
Labels: approved, lgtm, size/XXL

#817 `go mod tidy` after go/x/crypto update 0.32.0 -> 0.37.0
  go.mod
Labels: size/XS, approved, lgtm

#818 Improve test coverage for gem package manager
  packages/gem.go
  packages/gem_test.go
  packages/testdata/linux-gem-list-local.expected
  packages/testdata/linux-gem-list-local.stdout
  packages/testdata/linux-gem-outdated-local.expected
  packages/testdata/linux-gem-outdated-local.stdout
Labels: approved, lgtm, size/XXL

#823 Add InstalledRPMPackages snapshot tests
  packages/rpm_test.go
  packages/testdata/centos-7-1.rpm-query-all.stdout
  packages/testdata/centos-7-1.rpm-query-all.want
  packages/testdata/oracle-linux-8.rpm-query-all.stdout
  packages/testdata/oracle-linux-8.rpm-query-all.want
  packages/testdata/rhel-9-1.rpm-query-all.stdout
  packages/testdata/rhel-9-1.rpm-query-all.want
  packages/testdata/rocky-8-1.rpm-query-all.stdout
  packages/testdata/rocky-8-1.rpm-query-all.want
  packages/testdata/sles-12-1.rpm-query-all.stdout
  packages/testdata/sles-12-1.rpm-query-all.want
Labels: approved, lgtm, size/XXL

#822 Add debian (10,11,12) GetPackageUpdates output snapshots
  packages/apt_deb_test.go
  packages/testdata/debian-10-1.apt-get-full-upgrade.expected
  packages/testdata/debian-10-1.apt-get-full-upgrade.stdout
  packages/testdata/debian-11-1.apt-get-full-upgrade.expected
  packages/testdata/debian-11-1.apt-get-full-upgrade.stdout
  packages/testdata/debian-12-1.apt-get-full-upgrade.expected
  packages/testdata/debian-12-1.apt-get-full-upgrade.stdout
Labels: size/L, approved, lgtm

#824 cover packages_linux.go file with tests
  packages/packages_linux.go
  packages/packages_linux_test.go
Labels: size/L, approved, lgtm

#825 Refactor /inventory with dependency injection
  agentendpoint/agentendpoint.go
  agentendpoint/inventory.go
  inventory/inventory.go
  inventory/inventory_test.go
  osinfo/osinfo.go
  osinfo/osinfo_linux.go
  osinfo/osinfo_linux_test.go
  osinfo/osinfo_windows.go
  packages/packages.go
  packages/packages_linux.go
  packages/packages_windows.go
Labels: size/L, approved, lgtm

#826 cosmetic refactoring to osinfo package
  osinfo/osinfo.go
  osinfo/osinfo_linux_test.go
Labels: size/L, approved

#833 Fix rpm extractor, handle (none) value correctly.
  packages/rpm.go
  packages/rpm_test.go
  packages/testdata/centos-7-1.rpm-query-all.want
  packages/testdata/oracle-linux-8.rpm-query-all.want
  packages/testdata/rhel-9-1.rpm-query-all.want
  packages/testdata/rocky-8-1.rpm-query-all.want
  packages/testdata/sles-12-1.rpm-query-all.want
  pretty/pretty_test.go
Labels: approved, lgtm, size/M

#837 Add a simple no-op OS policy for user testing
  examples/OSPolicyAssignments/console/no-op.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test
