Repository GoogleCloudPlatform/osconfig, pull requests merged in 2025-04, with the labels that each got.

#804 Add output of some packagemanagers to the testdata
  packages/testdata/sles_12_zypper_patches
  packages/testdata/sles_15_zypper_patches
  packages/testdata/ubuntu_20_apt_get_full_upgrade
  packages/testdata/ubuntu_22_apt_get_full_upgrade
  packages/testdata/ubuntu_24_apt_get_full_upgrade
Labels: size/L, approved

#799 Update hash computation algorithm
  agentendpoint/agentendpoint.go
  agentendpoint/inventory.go
  agentendpoint/inventory_test.go
Labels: size/L, approved, lgtm

#809 Refactor OS Info package
  osinfo/osinfo.go
  osinfo/osinfo_linux.go
  osinfo/osinfo_linux_test.go
  osinfo/osinfo_windows.go
  packages/apt_deb.go
  packages/packages.go
  packages/yum.go
  packages/zypper.go
  pretty/pretty.go
  pretty/pretty_test.go
Labels: size/XL, approved, lgtm

#810 defaultSleeper: tolerate 10% difference to reduce test flakiness
  retryutil/retry_test.go
Labels: size/XS, approved, lgtm

#811 Introduce MatchSnapshot large test results matcher function, snapshot apt-deb GetPackageUpdates
  go.mod
  go.sum
  packages/apt_deb_test.go
  packages/testdata/ubuntu_20_apt_get_full_upgrade.expected
  packages/testdata/ubuntu_20_apt_get_full_upgrade.stdout
  packages/testdata/ubuntu_22_apt_get_full_upgrade.expected
  packages/testdata/ubuntu_22_apt_get_full_upgrade.stdout
  packages/testdata/ubuntu_24_apt_get_full_upgrade.expected
  packages/testdata/ubuntu_24_apt_get_full_upgrade.stdout
  util/utiltest/utiltest.go
  util/utiltest/utiltest_test.go
Labels: size/XL, approved, lgtm

#812 Snapshot ZypperPatches, ZypperUpdates (GetPackageUpdates) output for sles 12, 15 testdata
  packages/testdata/sles_12_zypper_list_patches.expected
  packages/testdata/sles_12_zypper_list_patches.stdout
  packages/testdata/sles_12_zypper_list_updates.expected
  packages/testdata/sles_12_zypper_list_updates.stdout
  packages/testdata/sles_15_zypper_list_patches.expected
  packages/testdata/sles_15_zypper_list_patches.stdout
  packages/testdata/sles_15_zypper_list_updates.expected
  packages/testdata/sles_15_zypper_list_updates.stdout
  packages/testdata/sles_15_zypper_patches
  packages/zypper_test.go
Labels: approved, lgtm, size/XXL

#813 Snapshot YumUpdates (GetPackageUpdates) output
  packages/apt_deb_test.go
  packages/testdata/centos-7-1.yum-check-update.stderr
  packages/testdata/centos-7-1.yum-check-update.stdout
  packages/testdata/centos-7-1.yum-update.expected
  packages/testdata/centos-7-1.yum-update.stderr
  packages/testdata/centos-7-1.yum-update.stdout
  packages/testdata/oracle-linux-8.yum-check-update.stderr
  packages/testdata/oracle-linux-8.yum-check-update.stdout
  packages/testdata/oracle-linux-8.yum-update.expected
  packages/testdata/oracle-linux-8.yum-update.stderr
  packages/testdata/oracle-linux-8.yum-update.stdout
  packages/testdata/rhel-7-1.yum-check-update.stderr
  packages/testdata/rhel-7-1.yum-check-update.stdout
  packages/testdata/rhel-7-1.yum-update.expected
  packages/testdata/rhel-7-1.yum-update.stderr
  packages/testdata/rhel-7-1.yum-update.stdout
  packages/testdata/rocky8-8.yum-check-update.stderr
  packages/testdata/rocky8-8.yum-check-update.stdout
  packages/testdata/rocky8-8.yum-update.expected
  packages/testdata/rocky8-8.yum-update.stderr
  packages/testdata/rocky8-8.yum-update.stdout
  packages/testdata/sles-12-1.zypper-list-patches.expected
  packages/testdata/sles-12-1.zypper-list-patches.stdout
  packages/testdata/sles-12-1.zypper-list-updates.expected
  packages/testdata/sles-12-1.zypper-list-updates.stdout
  packages/testdata/sles-15-1.zypper-list-patches.expected
  packages/testdata/sles-15-1.zypper-list-patches.stdout
  packages/testdata/sles-15-1.zypper-list-updates.expected
  packages/testdata/sles-15-1.zypper-list-updates.stdout
  packages/testdata/ubuntu-20.apt-get-full-upgrade.expected
  packages/testdata/ubuntu-20.apt-get-full-upgrade.stdout
  packages/testdata/ubuntu-22.apt-get-full-upgrade.expected
  packages/testdata/ubuntu-22.apt-get-full-upgrade.stdout
  packages/testdata/ubuntu-24.apt-get-full-upgrade.expected
  packages/testdata/ubuntu-24.apt-get-full-upgrade.stdout
  packages/yum_test.go
  packages/zypper_test.go
Labels: approved, lgtm, size/XXL
